version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://backend:3001
    ports:
      - '3000:80'
    depends_on:
      - backend
    restart: unless-stopped
