name: CI/CD Pipeline

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ main ]

jobs:
  ci:
    name: CI (lint, audit, Snyk, build images)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ─── Backend ────────────────────────────────────
      - name: Install backend deps
        run: cd backend && npm ci

      - name: Lint backend
        run: cd backend && npm run lint

      - name: Audit backend
        continue-on-error: true
        run: |
          cd backend
          npm audit --audit-level=moderate || true

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk test (backend)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          cd backend
          snyk test --severity-threshold=high || true

      # ─── Frontend ────────────────────────────────────
      - name: Install frontend deps
        run: cd frontend && npm ci

      - name: Lint frontend
        run: cd frontend && npm run lint

      - name: Snyk test (frontend)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          cd frontend
          snyk test --severity-threshold=high || true

      # ─── Build Docker images ────────────────────────
      - name: Build Docker images
        run: |
          docker build -t ci-backend:pr-backend ./backend
          docker build \
            --build-arg REACT_APP_API_URL=http://backend:3001 \
            -t ci-frontend:pr-frontend \
            ./frontend

  cd:
    name: CD (build & push prod images)
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ─── Build prod backend image ───────────────────
      - name: Build prod backend image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USER }}/ci-backend:latest \
            ./backend

      # ─── Build prod frontend image ──────────────────
      - name: Build prod frontend image
        run: |
          docker build \
            --build-arg REACT_APP_API_URL=https://api.prod \
            -t ${{ secrets.DOCKERHUB_USER }}/ci-frontend:latest \
            ./frontend

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} \
          | docker login --username ${{ secrets.DOCKERHUB_USER }} --password-stdin

      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USER }}/ci-backend:latest

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKERHUB_USER }}/ci-frontend:latest
